# SPDX-License-Identifier: BSL-1.0

default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-case-conflict
      # - id: no-commit-to-branch
      - id: check-added-large-files

  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: v14.0.6
  #   hooks:
  #     - id: clang-format
