local empty = juce.File.new()
assert(not empty:exists())
assert(not empty:existsAsFile())
assert(not empty:isDirectory())
assert(not empty:isRoot())

local thisFile = juce.File.getCurrentWorkingDirectory():getChildFile("File.lua")
assert(thisFile:exists())
assert(thisFile:existsAsFile())
assert(not thisFile:isDirectory())
assert(not thisFile:isRoot())
assert(not thisFile:isHidden())
assert(thisFile:getSize() > 0)
assert(thisFile:getFullPathName():isNotEmpty())
assert(thisFile:getFileName() == juce.String.new("File.lua"))
assert(thisFile:getFileExtension() == juce.String.new(".lua"))
assert(thisFile:getFileNameWithoutExtension() == juce.String.new("File"))
