name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx: [17, 20, 23]
        build_mode: ["Release"]
        compiler: ["gcc", "clang"]
      fail-fast: false
    name: ${{ matrix.compiler }} - ${{ matrix.cxx }} - ${{ matrix.build_mode }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Update apt
        run: sudo apt update -y

      - name: Install JUCE dependencies
        run: >
          sudo apt install -y
          ninja-build
          libasound2-dev
          libjack-jackd2-dev
          ladspa-sdk
          libcurl4-openssl-dev
          libfreetype6-dev
          libx11-dev
          libxcomposite-dev
          libxcursor-dev
          libxcursor-dev
          libxext-dev
          libxinerama-dev
          libxrandr-dev
          libxrender-dev
          libwebkit2gtk-4.0-dev
          libglu1-mesa-dev
          mesa-common-dev

      - name: Install LLVM
        if: matrix.compiler == 'clang'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14 all

      - name: Install conan
        run: |
          pip install conan
          conan config set general.revisions_enabled=1

      - name: CMake configure - GCC
        if: matrix.compiler == 'gcc'
        run: >
          cmake
          -S .
          -G Ninja
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.build_mode }}
          -D CMAKE_CXX_STANDARD="${{ matrix.cxx }}"

      - name: CMake configure - CLANG
        if: matrix.compiler == 'clang'
        run: >
          cmake
          -S .
          -G Ninja
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.build_mode }}
          -D CMAKE_CXX_STANDARD="${{ matrix.cxx }}"
          -D CMAKE_C_COMPILER="clang-14"
          -D CMAKE_CXX_COMPILER="clang++-14"
          -D CMAKE_UNITY_BUILD=ON
          -D MC_BUILD_WERROR=ON

      - name: CMake build
        run: cmake --build build --config ${{ matrix.build_mode }}

      - name: CTest
        run: ctest --test-dir build -C ${{ matrix.build_mode }} --output-on-failure
